

//var qx = window.qx;


/*
types that are not explicity registered
*/
declare module qx {}

   declare module qx.Bootstrap{} // Object
   declare module qx.Class{} // Object
   declare module qx.Interface{} // Object
   declare module qx.Mixin{} // Object
   declare module qx.Part{} // [Class qx.Part]
   declare module qx.Theme{} // Object
   declare module qx.application.AbstractGui{} // [Class qx.application.AbstractGui]
   declare module qx.application.Standalone{} // [Class qx.application.Standalone]
   declare module qx.bom.AnimationFrame{} // [Class qx.bom.AnimationFrame]
   declare module qx.bom.Cookie{} // Object
   declare module qx.bom.Document{} // Object
   declare module qx.bom.Element{} // Object
   declare module qx.bom.Event{} // Object
   declare module qx.bom.Font{} // [Class qx.bom.Font]
   declare module qx.bom.Iframe{} // Object
   declare module qx.bom.Input{} // Object
   declare module qx.bom.Label{} // Object
   declare module qx.bom.Range{} // Object
   declare module qx.bom.Selection{} // Object
   declare module qx.bom.Selector{} // Object
   declare module qx.bom.String{} // Object
   declare module qx.bom.Style{} // Object
   declare module qx.bom.Stylesheet{} // Object
   declare module qx.bom.Viewport{} // Object
   declare module qx.bom.client.Browser{} // Object
   declare module qx.bom.client.Css{} // Object
   declare module qx.bom.client.CssAnimation{} // Object
   declare module qx.bom.client.CssTransform{} // Object
   declare module qx.bom.client.EcmaScript{} // Object
   declare module qx.bom.client.Engine{} // Object
   declare module qx.bom.client.Event{} // Object
   declare module qx.bom.client.Html{} // Object
   declare module qx.bom.client.Json{} // Object
   declare module qx.bom.client.Locale{} // Object
   declare module qx.bom.client.OperatingSystem{} // Object
   declare module qx.bom.client.Plugin{} // Object
   declare module qx.bom.client.Scroll{} // Object
   declare module qx.bom.client.Stylesheet{} // Object
   declare module qx.bom.client.Transport{} // Object
   declare module qx.bom.client.Xml{} // Object
   declare module qx.bom.element.Animation{} // Object
   declare module qx.bom.element.AnimationCss{} // Object
   declare module qx.bom.element.AnimationHandle{} // [Class qx.bom.element.AnimationHandle]
   declare module qx.bom.element.AnimationJs{} // Object
   declare module qx.bom.element.Attribute{} // Object
   declare module qx.bom.element.Background{} // Object
   declare module qx.bom.element.BoxSizing{} // Object
   declare module qx.bom.element.Class{} // Object
   declare module qx.bom.element.Clip{} // Object
   declare module qx.bom.element.Cursor{} // Object
   declare module qx.bom.element.Decoration{} // Object
   declare module qx.bom.element.Dimension{} // Object
   declare module qx.bom.element.Location{} // Object
   declare module qx.bom.element.Opacity{} // Object
   declare module qx.bom.element.Scroll{} // Object
   declare module qx.bom.element.Style{} // Object
   declare module qx.bom.element.Transform{} // Object
   declare module qx.bom.request.Script{} // [Class qx.bom.request.Script]
   declare module qx.bom.webfonts.Manager{} // [Class qx.bom.webfonts.Manager]
   declare module qx.bom.webfonts.Validator{} // [Class qx.bom.webfonts.Validator]
   declare module qx.bom.webfonts.WebFont{} // [Class qx.bom.webfonts.WebFont]
   declare module qx.core.Aspect{} // Object
   declare module qx.core.Assert{} // Object
   declare module qx.core.AssertionError{} // [Class qx.core.AssertionError]
   declare module qx.core.BaseInit{} // Object
   declare module qx.core.Environment{} // Object
   declare module qx.core.GlobalError{} // [Class qx.core.GlobalError]
   declare module qx.core.Init{} // Object
   declare module qx.core.Object{} // [Class qx.core.Object]
   declare module qx.core.ObjectRegistry{} // Object
   declare module qx.core.Property{} // Object
   declare module qx.core.ValidationError{} // [Class qx.core.ValidationError]
   declare module qx.core.WindowError{} // [Class qx.core.WindowError]
   declare module qx.data.Array{} // [Class qx.data.Array]
   declare module qx.data.SingleValueBinding{} // Object
   declare module qx.dev.ObjectSummary{} // Object
   declare module qx.dev.StackTrace{} // Object
   declare module qx.dom.Element{} // Object
   declare module qx.dom.Hierarchy{} // Object
   declare module qx.dom.Node{} // Object
   declare module qx.event.AcceleratingTimer{} // [Class qx.event.AcceleratingTimer]
   declare module qx.event.Emitter{} // [Class qx.event.Emitter]
   declare module qx.event.GlobalError{} // Object
   declare module qx.event.Idle{} // [Class qx.event.Idle]
   declare module qx.event.Manager{} // [Class qx.event.Manager]
   declare module qx.event.Pool{} // [Class qx.event.Pool]
   declare module qx.event.Registration{} // Object
   declare module qx.event.Timer{} // [Class qx.event.Timer]
   declare module qx.event.dispatch.AbstractBubbling{} // [Class qx.event.dispatch.AbstractBubbling]
   declare module qx.event.dispatch.Direct{} // [Class qx.event.dispatch.Direct]
   declare module qx.event.dispatch.DomBubbling{} // [Class qx.event.dispatch.DomBubbling]
   declare module qx.event.dispatch.MouseCapture{} // [Class qx.event.dispatch.MouseCapture]
   declare module qx.event.handler.Appear{} // [Class qx.event.handler.Appear]
   declare module qx.event.handler.Application{} // [Class qx.event.handler.Application]
   declare module qx.event.handler.Capture{} // [Class qx.event.handler.Capture]
   declare module qx.event.handler.DragDrop{} // [Class qx.event.handler.DragDrop]
   declare module qx.event.handler.Element{} // [Class qx.event.handler.Element]
   declare module qx.event.handler.Focus{} // [Class qx.event.handler.Focus]
   declare module qx.event.handler.Iframe{} // [Class qx.event.handler.Iframe]
   declare module qx.event.handler.Input{} // [Class qx.event.handler.Input]
   declare module qx.event.handler.Keyboard{} // [Class qx.event.handler.Keyboard]
   declare module qx.event.handler.Mouse{} // [Class qx.event.handler.Mouse]
   declare module qx.event.handler.Object{} // [Class qx.event.handler.Object]
   declare module qx.event.handler.Offline{} // [Class qx.event.handler.Offline]
   declare module qx.event.handler.Orientation{} // [Class qx.event.handler.Orientation]
   declare module qx.event.handler.Touch{} // [Class qx.event.handler.Touch]
   declare module qx.event.handler.TouchCore{} // [Class qx.event.handler.TouchCore]
   declare module qx.event.handler.UserAction{} // [Class qx.event.handler.UserAction]
   declare module qx.event.handler.Window{} // [Class qx.event.handler.Window]
   declare module qx.event.type.Data{} // [Class qx.event.type.Data]
   declare module qx.event.type.Dom{} // [Class qx.event.type.Dom]
   declare module qx.event.type.Drag{} // [Class qx.event.type.Drag]
   declare module qx.event.type.Event{} // [Class qx.event.type.Event]
   declare module qx.event.type.Focus{} // [Class qx.event.type.Focus]
   declare module qx.event.type.KeyInput{} // [Class qx.event.type.KeyInput]
   declare module qx.event.type.KeySequence{} // [Class qx.event.type.KeySequence]
   declare module qx.event.type.Mouse{} // [Class qx.event.type.Mouse]
   declare module qx.event.type.MouseWheel{} // [Class qx.event.type.MouseWheel]
   declare module qx.event.type.Native{} // [Class qx.event.type.Native]
   declare module qx.event.type.Orientation{} // [Class qx.event.type.Orientation]
   declare module qx.event.type.Swipe{} // [Class qx.event.type.Swipe]
   declare module qx.event.type.Tap{} // [Class qx.event.type.Tap]
   declare module qx.event.type.Touch{} // [Class qx.event.type.Touch]
   declare module qx.event.util.Keyboard{} // Object
   declare module qx.html.Blocker{} // [Class qx.html.Blocker]
   declare module qx.html.Decorator{} // [Class qx.html.Decorator]
   declare module qx.html.Element{} // [Class qx.html.Element]
   declare module qx.html.Image{} // [Class qx.html.Image]
   declare module qx.html.Input{} // [Class qx.html.Input]
   declare module qx.html.Label{} // [Class qx.html.Label]
   declare module qx.html.Root{} // [Class qx.html.Root]
   declare module qx.io.ImageLoader{} // Object
   declare module qx.io.PartLoader{} // [Class qx.io.PartLoader]
   declare module qx.io.part.ClosurePart{} // [Class qx.io.part.ClosurePart]
   declare module qx.io.part.Package{} // [Class qx.io.part.Package]
   declare module qx.io.part.Part{} // [Class qx.io.part.Part]
   declare module qx.io.remote.Exchange{} // [Class qx.io.remote.Exchange]
   declare module qx.io.remote.Request{} // [Class qx.io.remote.Request]
   declare module qx.io.remote.RequestQueue{} // [Class qx.io.remote.RequestQueue]
   declare module qx.io.remote.Response{} // [Class qx.io.remote.Response]
   declare module qx.io.remote.transport.Abstract{} // [Class qx.io.remote.transport.Abstract]
   declare module qx.io.remote.transport.Iframe{} // [Class qx.io.remote.transport.Iframe]
   declare module qx.io.remote.transport.Script{} // [Class qx.io.remote.transport.Script]
   declare module qx.io.remote.transport.XmlHttp{} // [Class qx.io.remote.transport.XmlHttp]
   declare module qx.lang.Array{} // Object
   declare module qx.lang.Function{} // Object
   declare module qx.lang.Generics{} // Object
   declare module qx.lang.Json{} // Object
   declare module qx.lang.JsonImpl{} // [Class qx.lang.JsonImpl]
   declare module qx.lang.Number{} // Object
   declare module qx.lang.Object{} // Object
   declare module qx.lang.String{} // Object
   declare module qx.lang.Type{} // Object
   declare module qx.lang.normalize.Array{} // Object
   declare module qx.lang.normalize.Date{} // Object
   declare module qx.lang.normalize.Error{} // Object
   declare module qx.lang.normalize.Function{} // Object
   declare module qx.lang.normalize.Object{} // Object
   declare module qx.lang.normalize.String{} // Object
   declare module qx.locale.Date{} // Object
   declare module qx.locale.LocalizedString{} // [Class qx.locale.LocalizedString]
   declare module qx.locale.Manager{} // [Class qx.locale.Manager]
   declare module qx.locale.Number{} // Object
   declare module qx.log.Logger{} // Object
   declare module qx.log.appender.RingBuffer{} // [Class qx.log.appender.RingBuffer]
   declare module qx.module.Animation{} // Object
   declare module qx.module.Css{} // Object
   declare module qx.module.Event{} // Object
   declare module qx.module.Polyfill{} // Object
   declare module qx.theme.manager.Appearance{} // [Class qx.theme.manager.Appearance]
   declare module qx.theme.manager.Color{} // [Class qx.theme.manager.Color]
   declare module qx.theme.manager.Decoration{} // [Class qx.theme.manager.Decoration]
   declare module qx.theme.manager.Font{} // [Class qx.theme.manager.Font]
   declare module qx.theme.manager.Icon{} // [Class qx.theme.manager.Icon]
   declare module qx.theme.manager.Meta{} // [Class qx.theme.manager.Meta]
   declare module qx.type.BaseArray{} // [Class qx.type.BaseArray]
   declare module qx.type.BaseError{} // [Class qx.type.BaseError]
   declare module qx.type.BaseString{} // [Class qx.type.BaseString]
   declare module qx.ui.basic.Atom{} // [Class qx.ui.basic.Atom]
   declare module qx.ui.basic.Image{} // [Class qx.ui.basic.Image]
   declare module qx.ui.basic.Label{} // [Class qx.ui.basic.Label]
   declare module qx.ui.container.Composite{} // [Class qx.ui.container.Composite]
   declare module qx.ui.container.Scroll{} // [Class qx.ui.container.Scroll]
   declare module qx.ui.container.SlideBar{} // [Class qx.ui.container.SlideBar]
   declare module qx.ui.container.Stack{} // [Class qx.ui.container.Stack]
   declare module qx.ui.control.ColorPopup{} // [Class qx.ui.control.ColorPopup]
   declare module qx.ui.control.ColorSelector{} // [Class qx.ui.control.ColorSelector]
   declare module qx.ui.control.DateChooser{} // [Class qx.ui.control.DateChooser]
   declare module qx.ui.core.Blocker{} // [Class qx.ui.core.Blocker]
   declare module qx.ui.core.ColumnData{} // [Class qx.ui.core.ColumnData]
   declare module qx.ui.core.DecoratorFactory{} // [Class qx.ui.core.DecoratorFactory]
   declare module qx.ui.core.DragDropCursor{} // [Class qx.ui.core.DragDropCursor]
   declare module qx.ui.core.EventHandler{} // [Class qx.ui.core.EventHandler]
   declare module qx.ui.core.FocusHandler{} // [Class qx.ui.core.FocusHandler]
   declare module qx.ui.core.LayoutItem{} // [Class qx.ui.core.LayoutItem]
   declare module qx.ui.core.SingleSelectionManager{} // [Class qx.ui.core.SingleSelectionManager]
   declare module qx.ui.core.Spacer{} // [Class qx.ui.core.Spacer]
   declare module qx.ui.core.Widget{} // [Class qx.ui.core.Widget]
   declare module qx.ui.core.queue.Appearance{} // Object
   declare module qx.ui.core.queue.Dispose{} // Object
   declare module qx.ui.core.queue.Layout{} // Object
   declare module qx.ui.core.queue.Manager{} // Object
   declare module qx.ui.core.queue.Visibility{} // Object
   declare module qx.ui.core.queue.Widget{} // Object
   declare module qx.ui.core.scroll.AbstractScrollArea{} // [Class qx.ui.core.scroll.AbstractScrollArea]
   declare module qx.ui.core.scroll.NativeScrollBar{} // [Class qx.ui.core.scroll.NativeScrollBar]
   declare module qx.ui.core.scroll.ScrollBar{} // [Class qx.ui.core.scroll.ScrollBar]
   declare module qx.ui.core.scroll.ScrollPane{} // [Class qx.ui.core.scroll.ScrollPane]
   declare module qx.ui.core.scroll.ScrollSlider{} // [Class qx.ui.core.scroll.ScrollSlider]
   declare module qx.ui.core.selection.Abstract{} // [Class qx.ui.core.selection.Abstract]
   declare module qx.ui.core.selection.ScrollArea{} // [Class qx.ui.core.selection.ScrollArea]
   declare module qx.ui.core.selection.Widget{} // [Class qx.ui.core.selection.Widget]
   declare module qx.ui.decoration.Abstract{} // [Class qx.ui.decoration.Abstract]
   declare module qx.ui.decoration.AbstractBox{} // [Class qx.ui.decoration.AbstractBox]
   declare module qx.ui.decoration.Background{} // [Class qx.ui.decoration.Background]
   declare module qx.ui.decoration.Beveled{} // [Class qx.ui.decoration.Beveled]
   declare module qx.ui.decoration.BoxDiv{} // [Class qx.ui.decoration.BoxDiv]
   declare module qx.ui.decoration.DynamicDecorator{} // [Class qx.ui.decoration.DynamicDecorator]
   declare module qx.ui.decoration.Grid{} // [Class qx.ui.decoration.Grid]
   declare module qx.ui.decoration.GridDiv{} // [Class qx.ui.decoration.GridDiv]
   declare module qx.ui.decoration.HBox{} // [Class qx.ui.decoration.HBox]
   declare module qx.ui.decoration.Single{} // [Class qx.ui.decoration.Single]
   declare module qx.ui.decoration.Uniform{} // [Class qx.ui.decoration.Uniform]
   declare module qx.ui.decoration.VBox{} // [Class qx.ui.decoration.VBox]
   declare module qx.ui.decoration.css3.BorderImage{} // [Class qx.ui.decoration.css3.BorderImage]
   declare module qx.ui.embed.Html{} // [Class qx.ui.embed.Html]
   declare module qx.ui.form.AbstractField{} // [Class qx.ui.form.AbstractField]
   declare module qx.ui.form.AbstractSelectBox{} // [Class qx.ui.form.AbstractSelectBox]
   declare module qx.ui.form.Button{} // [Class qx.ui.form.Button]
   declare module qx.ui.form.CheckBox{} // [Class qx.ui.form.CheckBox]
   declare module qx.ui.form.HoverButton{} // [Class qx.ui.form.HoverButton]
   declare module qx.ui.form.List{} // [Class qx.ui.form.List]
   declare module qx.ui.form.ListItem{} // [Class qx.ui.form.ListItem]
   declare module qx.ui.form.MenuButton{} // [Class qx.ui.form.MenuButton]
   declare module qx.ui.form.PasswordField{} // [Class qx.ui.form.PasswordField]
   declare module qx.ui.form.RadioButton{} // [Class qx.ui.form.RadioButton]
   declare module qx.ui.form.RadioGroup{} // [Class qx.ui.form.RadioGroup]
   declare module qx.ui.form.RepeatButton{} // [Class qx.ui.form.RepeatButton]
   declare module qx.ui.form.SelectBox{} // [Class qx.ui.form.SelectBox]
   declare module qx.ui.form.Slider{} // [Class qx.ui.form.Slider]
   declare module qx.ui.form.Spinner{} // [Class qx.ui.form.Spinner]
   declare module qx.ui.form.TextArea{} // [Class qx.ui.form.TextArea]
   declare module qx.ui.form.TextField{} // [Class qx.ui.form.TextField]
   declare module qx.ui.form.ToggleButton{} // [Class qx.ui.form.ToggleButton]
   declare module qx.ui.groupbox.GroupBox{} // [Class qx.ui.groupbox.GroupBox]
   declare module qx.ui.indicator.ProgressBar{} // [Class qx.ui.indicator.ProgressBar]
   declare module qx.ui.layout.Abstract{} // [Class qx.ui.layout.Abstract]
   declare module qx.ui.layout.Atom{} // [Class qx.ui.layout.Atom]
   declare module qx.ui.layout.Basic{} // [Class qx.ui.layout.Basic]
   declare module qx.ui.layout.Canvas{} // [Class qx.ui.layout.Canvas]
   declare module qx.ui.layout.Dock{} // [Class qx.ui.layout.Dock]
   declare module qx.ui.layout.Flow{} // [Class qx.ui.layout.Flow]
   declare module qx.ui.layout.Grid{} // [Class qx.ui.layout.Grid]
   declare module qx.ui.layout.Grow{} // [Class qx.ui.layout.Grow]
   declare module qx.ui.layout.HBox{} // [Class qx.ui.layout.HBox]
   declare module qx.ui.layout.LineSizeIterator{} // [Class qx.ui.layout.LineSizeIterator]
   declare module qx.ui.layout.Util{} // Object
   declare module qx.ui.layout.VBox{} // [Class qx.ui.layout.VBox]
   declare module qx.ui.menu.AbstractButton{} // [Class qx.ui.menu.AbstractButton]
   declare module qx.ui.menu.Button{} // [Class qx.ui.menu.Button]
   declare module qx.ui.menu.ButtonLayout{} // [Class qx.ui.menu.ButtonLayout]
   declare module qx.ui.menu.CheckBox{} // [Class qx.ui.menu.CheckBox]
   declare module qx.ui.menu.Layout{} // [Class qx.ui.menu.Layout]
   declare module qx.ui.menu.Manager{} // [Class qx.ui.menu.Manager]
   declare module qx.ui.menu.Menu{} // [Class qx.ui.menu.Menu]
   declare module qx.ui.menu.MenuSlideBar{} // [Class qx.ui.menu.MenuSlideBar]
   declare module qx.ui.menu.Separator{} // [Class qx.ui.menu.Separator]
   declare module qx.ui.menubar.Button{} // [Class qx.ui.menubar.Button]
   declare module qx.ui.popup.Manager{} // [Class qx.ui.popup.Manager]
   declare module qx.ui.popup.Popup{} // [Class qx.ui.popup.Popup]
   declare module qx.ui.root.Abstract{} // [Class qx.ui.root.Abstract]
   declare module qx.ui.root.Application{} // [Class qx.ui.root.Application]
   declare module qx.ui.splitpane.Blocker{} // [Class qx.ui.splitpane.Blocker]
   declare module qx.ui.splitpane.HLayout{} // [Class qx.ui.splitpane.HLayout]
   declare module qx.ui.splitpane.Pane{} // [Class qx.ui.splitpane.Pane]
   declare module qx.ui.splitpane.Slider{} // [Class qx.ui.splitpane.Slider]
   declare module qx.ui.splitpane.Splitter{} // [Class qx.ui.splitpane.Splitter]
   declare module qx.ui.splitpane.VLayout{} // [Class qx.ui.splitpane.VLayout]
   declare module qx.ui.table.Table{} // [Class qx.ui.table.Table]
   declare module qx.ui.table.celleditor.AbstractField{} // [Class qx.ui.table.celleditor.AbstractField]
   declare module qx.ui.table.celleditor.SelectBox{} // [Class qx.ui.table.celleditor.SelectBox]
   declare module qx.ui.table.celleditor.TextField{} // [Class qx.ui.table.celleditor.TextField]
   declare module qx.ui.table.cellrenderer.Abstract{} // [Class qx.ui.table.cellrenderer.Abstract]
   declare module qx.ui.table.cellrenderer.AbstractImage{} // [Class qx.ui.table.cellrenderer.AbstractImage]
   declare module qx.ui.table.cellrenderer.Boolean{} // [Class qx.ui.table.cellrenderer.Boolean]
   declare module qx.ui.table.cellrenderer.Conditional{} // [Class qx.ui.table.cellrenderer.Conditional]
   declare module qx.ui.table.cellrenderer.Default{} // [Class qx.ui.table.cellrenderer.Default]
   declare module qx.ui.table.cellrenderer.Html{} // [Class qx.ui.table.cellrenderer.Html]
   declare module qx.ui.table.cellrenderer.Image{} // [Class qx.ui.table.cellrenderer.Image]
   declare module qx.ui.table.cellrenderer.Number{} // [Class qx.ui.table.cellrenderer.Number]
   declare module qx.ui.table.cellrenderer.Replace{} // [Class qx.ui.table.cellrenderer.Replace]
   declare module qx.ui.table.columnmenu.Button{} // [Class qx.ui.table.columnmenu.Button]
   declare module qx.ui.table.columnmenu.MenuItem{} // [Class qx.ui.table.columnmenu.MenuItem]
   declare module qx.ui.table.columnmodel.Basic{} // [Class qx.ui.table.columnmodel.Basic]
   declare module qx.ui.table.columnmodel.Resize{} // [Class qx.ui.table.columnmodel.Resize]
   declare module qx.ui.table.columnmodel.resizebehavior.Abstract{} // [Class qx.ui.table.columnmodel.resizebehavior.Abstract]
   declare module qx.ui.table.columnmodel.resizebehavior.Default{} // [Class qx.ui.table.columnmodel.resizebehavior.Default]
   declare module qx.ui.table.headerrenderer.Default{} // [Class qx.ui.table.headerrenderer.Default]
   declare module qx.ui.table.headerrenderer.HeaderCell{} // [Class qx.ui.table.headerrenderer.HeaderCell]
   declare module qx.ui.table.headerrenderer.Icon{} // [Class qx.ui.table.headerrenderer.Icon]
   declare module qx.ui.table.model.Abstract{} // [Class qx.ui.table.model.Abstract]
   declare module qx.ui.table.model.Remote{} // [Class qx.ui.table.model.Remote]
   declare module qx.ui.table.model.Simple{} // [Class qx.ui.table.model.Simple]
   declare module qx.ui.table.pane.CellEvent{} // [Class qx.ui.table.pane.CellEvent]
   declare module qx.ui.table.pane.Clipper{} // [Class qx.ui.table.pane.Clipper]
   declare module qx.ui.table.pane.FocusIndicator{} // [Class qx.ui.table.pane.FocusIndicator]
   declare module qx.ui.table.pane.Header{} // [Class qx.ui.table.pane.Header]
   declare module qx.ui.table.pane.Model{} // [Class qx.ui.table.pane.Model]
   declare module qx.ui.table.pane.Pane{} // [Class qx.ui.table.pane.Pane]
   declare module qx.ui.table.pane.Scroller{} // [Class qx.ui.table.pane.Scroller]
   declare module qx.ui.table.rowrenderer.Default{} // [Class qx.ui.table.rowrenderer.Default]
   declare module qx.ui.table.selection.Manager{} // [Class qx.ui.table.selection.Manager]
   declare module qx.ui.table.selection.Model{} // [Class qx.ui.table.selection.Model]
   declare module qx.ui.tabview.Page{} // [Class qx.ui.tabview.Page]
   declare module qx.ui.tabview.TabButton{} // [Class qx.ui.tabview.TabButton]
   declare module qx.ui.tabview.TabView{} // [Class qx.ui.tabview.TabView]
   declare module qx.ui.toolbar.Button{} // [Class qx.ui.toolbar.Button]
   declare module qx.ui.toolbar.Part{} // [Class qx.ui.toolbar.Part]
   declare module qx.ui.toolbar.PartContainer{} // [Class qx.ui.toolbar.PartContainer]
   declare module qx.ui.toolbar.Separator{} // [Class qx.ui.toolbar.Separator]
   declare module qx.ui.toolbar.ToolBar{} // [Class qx.ui.toolbar.ToolBar]
   declare module qx.ui.tooltip.Manager{} // [Class qx.ui.tooltip.Manager]
   declare module qx.ui.tooltip.ToolTip{} // [Class qx.ui.tooltip.ToolTip]
   declare module qx.ui.tree.Tree{} // [Class qx.ui.tree.Tree]
   declare module qx.ui.tree.TreeFile{} // [Class qx.ui.tree.TreeFile]
   declare module qx.ui.tree.TreeFolder{} // [Class qx.ui.tree.TreeFolder]
   declare module qx.ui.tree.core.AbstractItem{} // [Class qx.ui.tree.core.AbstractItem]
   declare module qx.ui.tree.core.AbstractTreeItem{} // [Class qx.ui.tree.core.AbstractTreeItem]
   declare module qx.ui.tree.core.FolderOpenButton{} // [Class qx.ui.tree.core.FolderOpenButton]
   declare module qx.ui.tree.selection.SelectionManager{} // [Class qx.ui.tree.selection.SelectionManager]
   declare module qx.ui.treevirtual.DefaultDataCellRenderer{} // [Class qx.ui.treevirtual.DefaultDataCellRenderer]
   declare module qx.ui.treevirtual.SelectionManager{} // [Class qx.ui.treevirtual.SelectionManager]
   declare module qx.ui.treevirtual.SimpleTreeDataCellRenderer{} // [Class qx.ui.treevirtual.SimpleTreeDataCellRenderer]
   declare module qx.ui.treevirtual.SimpleTreeDataModel{} // [Class qx.ui.treevirtual.SimpleTreeDataModel]
   declare module qx.ui.treevirtual.SimpleTreeDataRowRenderer{} // [Class qx.ui.treevirtual.SimpleTreeDataRowRenderer]
   declare module qx.ui.treevirtual.TreeVirtual{} // [Class qx.ui.treevirtual.TreeVirtual]
   declare module qx.ui.window.Manager{} // [Class qx.ui.window.Manager]
   declare module qx.ui.window.Window{} // [Class qx.ui.window.Window]
   declare module qx.util.AliasManager{} // [Class qx.util.AliasManager]
   declare module qx.util.ColorUtil{} // Object
   declare module qx.util.DeferredCall{} // [Class qx.util.DeferredCall]
   declare module qx.util.DeferredCallManager{} // [Class qx.util.DeferredCallManager]
   declare module qx.util.DisposeUtil{} // Object
   declare module qx.util.LibraryManager{} // [Class qx.util.LibraryManager]
   declare module qx.util.OOUtil{} // Object
   declare module qx.util.ObjectPool{} // [Class qx.util.ObjectPool]
   declare module qx.util.PropertyUtil{} // Object
   declare module qx.util.ResourceManager{} // [Class qx.util.ResourceManager]
   declare module qx.util.RingBuffer{} // [Class qx.util.RingBuffer]
   declare module qx.util.StringBuilder{} // [Class qx.util.StringBuilder]
   declare module qx.util.StringEscape{} // Object
   declare module qx.util.StringSplit{} // Object
   declare module qx.util.TimerManager{} // [Class qx.util.TimerManager]
   declare module qx.util.Uri{} // Object
   declare module qx.util.ValueManager{} // [Class qx.util.ValueManager]
   declare module qx.util.format.DateFormat{} // [Class qx.util.format.DateFormat]
   declare module qx.util.format.NumberFormat{} // [Class qx.util.format.NumberFormat]
   declare module qx.util.placement.AbstractAxis{} // [Class qx.util.placement.AbstractAxis]
   declare module qx.util.placement.BestFitAxis{} // Object
   declare module qx.util.placement.DirectAxis{} // Object
   declare module qx.util.placement.KeepAlignAxis{} // Object
   declare module qx.util.placement.Placement{} // [Class qx.util.placement.Placement]
   declare module qx.xml.Document{} // Object
   declare module qxWeb{} // [Class qxWeb]
   declare module sharedfrontend.Localization{} // [Class sharedfrontend.Localization]
	declare module webfrontend {}
   declare module webfrontend.Application{} // [Class webfrontend.Application]
   declare module webfrontend.Login{} // [Class webfrontend.Login]
   declare module webfrontend.Util{} // [Class webfrontend.Util]
   declare module webfrontend.base.GameObjects{} // Object
   declare module webfrontend.base.Timer{} // [Class webfrontend.base.Timer]
   declare module webfrontend.city.CityLayout{} // [Class webfrontend.city.CityLayout]
   declare module webfrontend.city.CityObject{} // [Class webfrontend.city.CityObject]
   declare module webfrontend.config.Chat{} // [Class webfrontend.config.Chat]
   declare module webfrontend.config.Config{} // [Class webfrontend.config.Config]
   declare module webfrontend.data.Achievement{} // [Class webfrontend.data.Achievement]
   declare module webfrontend.data.Alliance{} // [Class webfrontend.data.Alliance]
   declare module webfrontend.data.AllianceDataModel{} // [Class webfrontend.data.AllianceDataModel]
   declare module webfrontend.data.AllianceForum{} // [Class webfrontend.data.AllianceForum]
   declare module webfrontend.data.AllianceInvitation{} // [Class webfrontend.data.AllianceInvitation]
   declare module webfrontend.data.AllianceResourceDataModel{} // [Class webfrontend.data.AllianceResourceDataModel]
   declare module webfrontend.data.Chat{} // [Class webfrontend.data.Chat]
   declare module webfrontend.data.City{} // [Class webfrontend.data.City]
   declare module webfrontend.data.DataContract.Contracts{} // Object
   declare module webfrontend.data.DataContract.Translator{} // [Class webfrontend.data.DataContract.Translator]
   declare module webfrontend.data.Enlightenment{} // [Class webfrontend.data.Enlightenment]
   declare module webfrontend.data.Events{} // [Class webfrontend.data.Events]
   declare module webfrontend.data.FriendInvitation{} // [Class webfrontend.data.FriendInvitation]
   declare module webfrontend.data.FriendList{} // [Class webfrontend.data.FriendList]
   declare module webfrontend.data.IgnoreList{} // [Class webfrontend.data.IgnoreList]
   declare module webfrontend.data.Inventory{} // [Class webfrontend.data.Inventory]
   declare module webfrontend.data.Mail{} // [Class webfrontend.data.Mail]
   declare module webfrontend.data.MailHeaderDataModel{} // [Class webfrontend.data.MailHeaderDataModel]
   declare module webfrontend.data.PalaceInfo{} // [Class webfrontend.data.PalaceInfo]
   declare module webfrontend.data.Player{} // [Class webfrontend.data.Player]
   declare module webfrontend.data.PlayerListDataModel{} // [Class webfrontend.data.PlayerListDataModel]
   declare module webfrontend.data.Quest{} // [Class webfrontend.data.Quest]
   declare module webfrontend.data.QuickUseItems{} // [Class webfrontend.data.QuickUseItems]
   declare module webfrontend.data.Report{} // [Class webfrontend.data.Report]
   declare module webfrontend.data.ReportHeaderDataModel{} // [Class webfrontend.data.ReportHeaderDataModel]
   declare module webfrontend.data.Server{} // [Class webfrontend.data.Server]
   declare module webfrontend.data.ServerTime{} // [Class webfrontend.data.ServerTime]
   declare module webfrontend.data.ShopCatalog{} // [Class webfrontend.data.ShopCatalog]
   declare module webfrontend.data.SimpleColFormattingDataModel{} // [Class webfrontend.data.SimpleColFormattingDataModel]
   declare module webfrontend.data.SimpleTreeDataModelCustom{} // [Class webfrontend.data.SimpleTreeDataModelCustom]
   declare module webfrontend.data.Substitution{} // [Class webfrontend.data.Substitution]
   declare module webfrontend.data.Tech{} // [Class webfrontend.data.Tech]
   declare module webfrontend.data.TradeMinister{} // [Class webfrontend.data.TradeMinister]
   declare module webfrontend.data.TreeDataCellRendererCustom{} // [Class webfrontend.data.TreeDataCellRendererCustom]
   declare module webfrontend.draw.BackgroundTextNode{} // [Class webfrontend.draw.BackgroundTextNode]
   declare module webfrontend.draw.BoxNode{} // [Class webfrontend.draw.BoxNode]
   declare module webfrontend.draw.CameraFogNode{} // [Class webfrontend.draw.CameraFogNode]
   declare module webfrontend.draw.CameraImageNode{} // [Class webfrontend.draw.CameraImageNode]
   declare module webfrontend.draw.DivNode{} // [Class webfrontend.draw.DivNode]
   declare module webfrontend.draw.EffectNode{} // [Class webfrontend.draw.EffectNode]
   declare module webfrontend.draw.ImageNode{} // [Class webfrontend.draw.ImageNode]
   declare module webfrontend.draw.Node{} // [Class webfrontend.draw.Node]
   declare module webfrontend.draw.ProgressBarNode{} // [Class webfrontend.draw.ProgressBarNode]
   declare module webfrontend.draw.Scene{} // [Class webfrontend.draw.Scene]
   declare module webfrontend.draw.Widget{} // [Class webfrontend.draw.Widget]
   declare module webfrontend.gui.Achievement.AchievementLayoutItem{} // [Class webfrontend.gui.Achievement.AchievementLayoutItem]
   declare module webfrontend.gui.Achievement.AchievementModel{} // [Class webfrontend.gui.Achievement.AchievementModel]
   declare module webfrontend.gui.Achievement.CategorySelection{} // [Class webfrontend.gui.Achievement.CategorySelection]
   declare module webfrontend.gui.Achievement.ChallengeHistoryModel{} // [Class webfrontend.gui.Achievement.ChallengeHistoryModel]
   declare module webfrontend.gui.Achievement.InfoWindow{} // [Class webfrontend.gui.Achievement.InfoWindow]
   declare module webfrontend.gui.Achievement.Model{} // [Class webfrontend.gui.Achievement.Model]
   declare module webfrontend.gui.Achievement.NearlyCompletedItem{} // [Class webfrontend.gui.Achievement.NearlyCompletedItem]
   declare module webfrontend.gui.Achievement.NotificationPopup{} // [Class webfrontend.gui.Achievement.NotificationPopup]
   declare module webfrontend.gui.Achievement.OverviewCategoryProgressItem{} // [Class webfrontend.gui.Achievement.OverviewCategoryProgressItem]
   declare module webfrontend.gui.Achievement.OverviewDisplay{} // [Class webfrontend.gui.Achievement.OverviewDisplay]
   declare module webfrontend.gui.Achievement.PageDisplay{} // [Class webfrontend.gui.Achievement.PageDisplay]
   declare module webfrontend.gui.Achievement.RecentlyCompletedItem{} // [Class webfrontend.gui.Achievement.RecentlyCompletedItem]
   declare module webfrontend.gui.Achievement.ServerFirstModel{} // [Class webfrontend.gui.Achievement.ServerFirstModel]
   declare module webfrontend.gui.Achievement.ServerFirstPage{} // [Class webfrontend.gui.Achievement.ServerFirstPage]
   declare module webfrontend.gui.Achievement.SpecialsTabView{} // [Class webfrontend.gui.Achievement.SpecialsTabView]
   declare module webfrontend.gui.Achievement.TabPageNormal{} // [Class webfrontend.gui.Achievement.TabPageNormal]
   declare module webfrontend.gui.AdWindow{} // [Class webfrontend.gui.AdWindow]
   declare module webfrontend.gui.Alliance.DiplomacyPage{} // [Class webfrontend.gui.Alliance.DiplomacyPage]
   declare module webfrontend.gui.Alliance.Forum.MainPage{} // [Class webfrontend.gui.Alliance.Forum.MainPage]
   declare module webfrontend.gui.Alliance.Forum.PostItem{} // [Class webfrontend.gui.Alliance.Forum.PostItem]
   declare module webfrontend.gui.Alliance.Forum.PostPage{} // [Class webfrontend.gui.Alliance.Forum.PostPage]
   declare module webfrontend.gui.Alliance.Forum.PropertiesPage{} // [Class webfrontend.gui.Alliance.Forum.PropertiesPage]
   declare module webfrontend.gui.Alliance.Forum.ThreadLabel{} // [Class webfrontend.gui.Alliance.Forum.ThreadLabel]
   declare module webfrontend.gui.Alliance.Forum.ThreadPage{} // [Class webfrontend.gui.Alliance.Forum.ThreadPage]
   declare module webfrontend.gui.Alliance.Forum.TitleLabel{} // [Class webfrontend.gui.Alliance.Forum.TitleLabel]
   declare module webfrontend.gui.Alliance.Info.AchievementsPage{} // [Class webfrontend.gui.Alliance.Info.AchievementsPage]
   declare module webfrontend.gui.Alliance.Info.InfoPage{} // [Class webfrontend.gui.Alliance.Info.InfoPage]
   declare module webfrontend.gui.Alliance.Info.MainWindow{} // [Class webfrontend.gui.Alliance.Info.MainWindow]
   declare module webfrontend.gui.Alliance.Info.MemberList{} // [Class webfrontend.gui.Alliance.Info.MemberList]
   declare module webfrontend.gui.Alliance.Info.NamesPage{} // [Class webfrontend.gui.Alliance.Info.NamesPage]
   declare module webfrontend.gui.Alliance.Info.PageBase{} // [Class webfrontend.gui.Alliance.Info.PageBase]
   declare module webfrontend.gui.Alliance.Info.Reward.RewardEditWindow{} // [Class webfrontend.gui.Alliance.Info.Reward.RewardEditWindow]
   declare module webfrontend.gui.Alliance.InvitationItem{} // [Class webfrontend.gui.Alliance.InvitationItem]
   declare module webfrontend.gui.Alliance.MainWidget{} // [Class webfrontend.gui.Alliance.MainWidget]
   declare module webfrontend.gui.Alliance.MemberRightsPage{} // [Class webfrontend.gui.Alliance.MemberRightsPage]
   declare module webfrontend.gui.Alliance.MemberStatusPage{} // [Class webfrontend.gui.Alliance.MemberStatusPage]
   declare module webfrontend.gui.Alliance.MembersPage{} // [Class webfrontend.gui.Alliance.MembersPage]
   declare module webfrontend.gui.Alliance.OverviewPage{} // [Class webfrontend.gui.Alliance.OverviewPage]
   declare module webfrontend.gui.Alliance.ShrinePage{} // [Class webfrontend.gui.Alliance.ShrinePage]
   declare module webfrontend.gui.Alliance.SupporterRankingsPage{} // [Class webfrontend.gui.Alliance.SupporterRankingsPage]
   declare module webfrontend.gui.Alliance.VirtuesPage{} // [Class webfrontend.gui.Alliance.VirtuesPage]
   declare module webfrontend.gui.AllianceInvitationPopup{} // [Class webfrontend.gui.AllianceInvitationPopup]
   declare module webfrontend.gui.BuildingDetailView{} // [Class webfrontend.gui.BuildingDetailView]
   declare module webfrontend.gui.BuildingPlaceDetailView{} // [Class webfrontend.gui.BuildingPlaceDetailView]
   declare module webfrontend.gui.BuildingQueue{} // [Class webfrontend.gui.BuildingQueue]
   declare module webfrontend.gui.CastleCustomization.MainWindow{} // [Class webfrontend.gui.CastleCustomization.MainWindow]
   declare module webfrontend.gui.CastleCustomization.SelectWidget{} // [Class webfrontend.gui.CastleCustomization.SelectWidget]
   declare module webfrontend.gui.CastleCustomization.Util{} // Object
   declare module webfrontend.gui.Chat{} // [Class webfrontend.gui.Chat]
   declare module webfrontend.gui.CityBarWidget{} // [Class webfrontend.gui.CityBarWidget]
   declare module webfrontend.gui.CityCommandInfoView{} // [Class webfrontend.gui.CityCommandInfoView]
   declare module webfrontend.gui.CityDefenseInfoView{} // [Class webfrontend.gui.CityDefenseInfoView]
   declare module webfrontend.gui.CityDetailView{} // [Class webfrontend.gui.CityDetailView]
   declare module webfrontend.gui.CityGroupsWidget{} // [Class webfrontend.gui.CityGroupsWidget]
   declare module webfrontend.gui.CityInfoPage{} // [Class webfrontend.gui.CityInfoPage]
   declare module webfrontend.gui.CityInfoView{} // [Class webfrontend.gui.CityInfoView]
   declare module webfrontend.gui.CityNotesWidget{} // [Class webfrontend.gui.CityNotesWidget]
   declare module webfrontend.gui.CityTradeInfoView{} // [Class webfrontend.gui.CityTradeInfoView]
   declare module webfrontend.gui.ConfirmationWidget{} // [Class webfrontend.gui.ConfirmationWidget]
   declare module webfrontend.gui.Credits{} // [Class webfrontend.gui.Credits]
   declare module webfrontend.gui.DailyRewardWidget{} // [Class webfrontend.gui.DailyRewardWidget]
   declare module webfrontend.gui.DebugCommandWindow{} // [Class webfrontend.gui.DebugCommandWindow]
   declare module webfrontend.gui.DefenseMinisterAutoRecruitTab{} // [Class webfrontend.gui.DefenseMinisterAutoRecruitTab]
   declare module webfrontend.gui.DetailView{} // [Class webfrontend.gui.DetailView]
   declare module webfrontend.gui.DungeonDetailView{} // [Class webfrontend.gui.DungeonDetailView]
   declare module webfrontend.gui.EndSubstitutionWidget{} // [Class webfrontend.gui.EndSubstitutionWidget]
   declare module webfrontend.gui.EventWindow{} // [Class webfrontend.gui.EventWindow]
   declare module webfrontend.gui.FoodCityOverviewWidget{} // [Class webfrontend.gui.FoodCityOverviewWidget]
   declare module webfrontend.gui.FoodWarningsWindow{} // [Class webfrontend.gui.FoodWarningsWindow]
   declare module webfrontend.gui.FortuneTeller.Card{} // [Class webfrontend.gui.FortuneTeller.Card]
   declare module webfrontend.gui.FortuneTeller.LargeCardDisplay{} // [Class webfrontend.gui.FortuneTeller.LargeCardDisplay]
   declare module webfrontend.gui.FortuneTeller.MainWindow{} // [Class webfrontend.gui.FortuneTeller.MainWindow]
   declare module webfrontend.gui.FortuneTeller.Selection{} // [Class webfrontend.gui.FortuneTeller.Selection]
   declare module webfrontend.gui.FortuneTeller.Util{} // Object
   declare module webfrontend.gui.FortuneTeller.WelcomeScreen{} // [Class webfrontend.gui.FortuneTeller.WelcomeScreen]
   declare module webfrontend.gui.Guide.ConditionArrow{} // [Class webfrontend.gui.Guide.ConditionArrow]
   declare module webfrontend.gui.Guide.ConditionContainer{} // [Class webfrontend.gui.Guide.ConditionContainer]
   declare module webfrontend.gui.Guide.ConditionVoidResourceBody{} // [Class webfrontend.gui.Guide.ConditionVoidResourceBody]
   declare module webfrontend.gui.Guide.MainWindow{} // [Class webfrontend.gui.Guide.MainWindow]
   declare module webfrontend.gui.Guide.MinisterHint{} // [Class webfrontend.gui.Guide.MinisterHint]
   declare module webfrontend.gui.Guide.Page.Artifacts{} // [Class webfrontend.gui.Guide.Page.Artifacts]
   declare module webfrontend.gui.Guide.Page.CityDefense{} // [Class webfrontend.gui.Guide.Page.CityDefense]
   declare module webfrontend.gui.Guide.Page.Raiding{} // [Class webfrontend.gui.Guide.Page.Raiding]
   declare module webfrontend.gui.Guide.Page.ResourceProduction{} // [Class webfrontend.gui.Guide.Page.ResourceProduction]
   declare module webfrontend.gui.Guide.Page.SecondCity{} // [Class webfrontend.gui.Guide.Page.SecondCity]
   declare module webfrontend.gui.Guide.SubPage.Raiding.BossRaids.GeneralAndTypes{} // [Class webfrontend.gui.Guide.SubPage.Raiding.BossRaids.GeneralAndTypes]
   declare module webfrontend.gui.Guide.SubPage.Raiding.BossRaids.LootAndRestrictions{} // [Class webfrontend.gui.Guide.SubPage.Raiding.BossRaids.LootAndRestrictions]
   declare module webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Base{} // [Class webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Base]
   declare module webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Loot{} // [Class webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Loot]
   declare module webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Progress{} // [Class webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Progress]
   declare module webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Types{} // [Class webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Types]
   declare module webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Weakness{} // [Class webfrontend.gui.Guide.SubPage.Raiding.DungeonRaids.Weakness]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Base{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Base]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Food{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Food]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Gold{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Gold]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Iron{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Iron]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Stone{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Stone]
   declare module webfrontend.gui.Guide.SubPage.ResourceProduction.Wood{} // [Class webfrontend.gui.Guide.SubPage.ResourceProduction.Wood]
   declare module webfrontend.gui.InfoNavigatorPage{} // [Class webfrontend.gui.InfoNavigatorPage]
   declare module webfrontend.gui.InfoNavigatorWidget{} // [Class webfrontend.gui.InfoNavigatorWidget]
   declare module webfrontend.gui.InfoWidget{} // [Class webfrontend.gui.InfoWidget]
   declare module webfrontend.gui.ItemsWidget{} // [Class webfrontend.gui.ItemsWidget]
   declare module webfrontend.gui.Mail.Contacts.ListItem{} // [Class webfrontend.gui.Mail.Contacts.ListItem]
   declare module webfrontend.gui.Mail.Contacts.MainWindow{} // [Class webfrontend.gui.Mail.Contacts.MainWindow]
   declare module webfrontend.gui.Mail.Contacts.TabAlliance{} // [Class webfrontend.gui.Mail.Contacts.TabAlliance]
   declare module webfrontend.gui.Mail.Contacts.TabBase{} // [Class webfrontend.gui.Mail.Contacts.TabBase]
   declare module webfrontend.gui.Mail.Contacts.TabFriends{} // [Class webfrontend.gui.Mail.Contacts.TabFriends]
   declare module webfrontend.gui.Mail.DistributionLists.EditListItem{} // [Class webfrontend.gui.Mail.DistributionLists.EditListItem]
   declare module webfrontend.gui.Mail.DistributionLists.EditWindow{} // [Class webfrontend.gui.Mail.DistributionLists.EditWindow]
   declare module webfrontend.gui.Mail.DistributionLists.ListItem{} // [Class webfrontend.gui.Mail.DistributionLists.ListItem]
   declare module webfrontend.gui.Mail.ListWidget{} // [Class webfrontend.gui.Mail.ListWidget]
   declare module webfrontend.gui.Mail.ReadMailPage{} // [Class webfrontend.gui.Mail.ReadMailPage]
   declare module webfrontend.gui.Mail.SendMailWidget{} // [Class webfrontend.gui.Mail.SendMailWidget]
   declare module webfrontend.gui.MapSelectorBarWidget{} // [Class webfrontend.gui.MapSelectorBarWidget]
   declare module webfrontend.gui.MentorWidget{} // [Class webfrontend.gui.MentorWidget]
   declare module webfrontend.gui.MinisterInfo.AppointMinisterContainer{} // [Class webfrontend.gui.MinisterInfo.AppointMinisterContainer]
   declare module webfrontend.gui.MinisterInfo.Base{} // [Class webfrontend.gui.MinisterInfo.Base]
   declare module webfrontend.gui.MinisterInfo.Build{} // [Class webfrontend.gui.MinisterInfo.Build]
   declare module webfrontend.gui.MinisterInfo.Defense{} // [Class webfrontend.gui.MinisterInfo.Defense]
   declare module webfrontend.gui.MinisterInfo.Page.Base{} // [Class webfrontend.gui.MinisterInfo.Page.Base]
   declare module webfrontend.gui.MinisterInfo.Page.BuildOptions{} // [Class webfrontend.gui.MinisterInfo.Page.BuildOptions]
   declare module webfrontend.gui.MinisterInfo.Page.DefenseOptions{} // [Class webfrontend.gui.MinisterInfo.Page.DefenseOptions]
   declare module webfrontend.gui.MinisterInfo.Page.TradeOptions{} // [Class webfrontend.gui.MinisterInfo.Page.TradeOptions]
   declare module webfrontend.gui.MinisterInfo.Page.WarOptions{} // [Class webfrontend.gui.MinisterInfo.Page.WarOptions]
   declare module webfrontend.gui.MinisterInfo.Trade{} // [Class webfrontend.gui.MinisterInfo.Trade]
   declare module webfrontend.gui.MinisterInfo.War{} // [Class webfrontend.gui.MinisterInfo.War]
   declare module webfrontend.gui.MinisterMerchandiseWidget{} // [Class webfrontend.gui.MinisterMerchandiseWidget]
   declare module webfrontend.gui.MoongateDetailView{} // [Class webfrontend.gui.MoongateDetailView]
   declare module webfrontend.gui.MoveBuildingDetailView{} // [Class webfrontend.gui.MoveBuildingDetailView]
   declare module webfrontend.gui.NewCityView{} // [Class webfrontend.gui.NewCityView]
   declare module webfrontend.gui.NewPlayerWidget{} // [Class webfrontend.gui.NewPlayerWidget]
   declare module webfrontend.gui.NewsletterPage{} // [Class webfrontend.gui.NewsletterPage]
   declare module webfrontend.gui.NewsletterWindow{} // [Class webfrontend.gui.NewsletterWindow]
   declare module webfrontend.gui.OptionsWidget{} // [Class webfrontend.gui.OptionsWidget]
   declare module webfrontend.gui.OrderDetail.Header{} // [Class webfrontend.gui.OrderDetail.Header]
   declare module webfrontend.gui.OrderDetail.LootDisplay{} // [Class webfrontend.gui.OrderDetail.LootDisplay]
   declare module webfrontend.gui.OrderDetail.MainPage{} // [Class webfrontend.gui.OrderDetail.MainPage]
   declare module webfrontend.gui.OrderDetail.MoongateDisplay{} // [Class webfrontend.gui.OrderDetail.MoongateDisplay]
   declare module webfrontend.gui.OrderDetail.RaidTimeDisplay{} // [Class webfrontend.gui.OrderDetail.RaidTimeDisplay]
   declare module webfrontend.gui.OrderDetail.UnitDisplay{} // [Class webfrontend.gui.OrderDetail.UnitDisplay]
   declare module webfrontend.gui.OverlayWidget{} // [Class webfrontend.gui.OverlayWidget]
   declare module webfrontend.gui.OverlayWindow{} // [Class webfrontend.gui.OverlayWindow]
   declare module webfrontend.gui.Overviews.Alliance.DefenseHistoryPage{} // [Class webfrontend.gui.Overviews.Alliance.DefenseHistoryPage]
   declare module webfrontend.gui.Overviews.Alliance.EditEnlightenmentCommentWindow{} // [Class webfrontend.gui.Overviews.Alliance.EditEnlightenmentCommentWindow]
   declare module webfrontend.gui.Overviews.Alliance.EnlightenedCitiesPage{} // [Class webfrontend.gui.Overviews.Alliance.EnlightenedCitiesPage]
   declare module webfrontend.gui.Overviews.Alliance.IncomingAttacksPage{} // [Class webfrontend.gui.Overviews.Alliance.IncomingAttacksPage]
   declare module webfrontend.gui.Overviews.Alliance.OffenseHistoryPage{} // [Class webfrontend.gui.Overviews.Alliance.OffenseHistoryPage]
   declare module webfrontend.gui.Overviews.Alliance.OutgoingAttacksPage{} // [Class webfrontend.gui.Overviews.Alliance.OutgoingAttacksPage]
   declare module webfrontend.gui.Overviews.Alliance.Util{} // Object
   declare module webfrontend.gui.Overviews.AllianceOverviewsPage{} // [Class webfrontend.gui.Overviews.AllianceOverviewsPage]
   declare module webfrontend.gui.Overviews.MainWindow{} // [Class webfrontend.gui.Overviews.MainWindow]
   declare module webfrontend.gui.Overviews.Minister.BuildingQueuePage{} // [Class webfrontend.gui.Overviews.Minister.BuildingQueuePage]
   declare module webfrontend.gui.Overviews.Minister.CommandPage{} // [Class webfrontend.gui.Overviews.Minister.CommandPage]
   declare module webfrontend.gui.Overviews.Minister.DefensePage{} // [Class webfrontend.gui.Overviews.Minister.DefensePage]
   declare module webfrontend.gui.Overviews.Minister.ResourcePage{} // [Class webfrontend.gui.Overviews.Minister.ResourcePage]
   declare module webfrontend.gui.Overviews.MinisterOverviewsPage{} // [Class webfrontend.gui.Overviews.MinisterOverviewsPage]
   declare module webfrontend.gui.PatchNotesWidget{} // [Class webfrontend.gui.PatchNotesWidget]
   declare module webfrontend.gui.PlayerInfo.AchievementsPage{} // [Class webfrontend.gui.PlayerInfo.AchievementsPage]
   declare module webfrontend.gui.PlayerInfo.CitiesPage{} // [Class webfrontend.gui.PlayerInfo.CitiesPage]
   declare module webfrontend.gui.PlayerInfo.InfoPage{} // [Class webfrontend.gui.PlayerInfo.InfoPage]
   declare module webfrontend.gui.PlayerInfo.LouAchievementsPage{} // [Class webfrontend.gui.PlayerInfo.LouAchievementsPage]
   declare module webfrontend.gui.PlayerInfo.MainWindow{} // [Class webfrontend.gui.PlayerInfo.MainWindow]
   declare module webfrontend.gui.PlayerInfo.PageBase{} // [Class webfrontend.gui.PlayerInfo.PageBase]
   declare module webfrontend.gui.PlayerInfo.RewardEditWindow{} // [Class webfrontend.gui.PlayerInfo.RewardEditWindow]
   declare module webfrontend.gui.PopupChain{} // [Class webfrontend.gui.PopupChain]
   declare module webfrontend.gui.PopupWindow{} // [Class webfrontend.gui.PopupWindow]
   declare module webfrontend.gui.QuestListWidget{} // [Class webfrontend.gui.QuestListWidget]
   declare module webfrontend.gui.QuestTrackerWidget{} // [Class webfrontend.gui.QuestTrackerWidget]
   declare module webfrontend.gui.QuestWidget{} // [Class webfrontend.gui.QuestWidget]
   declare module webfrontend.gui.Queue{} // [Class webfrontend.gui.Queue]
   declare module webfrontend.gui.Rankings.Challenges{} // [Class webfrontend.gui.Rankings.Challenges]
   declare module webfrontend.gui.Rankings.ChallengesDataModel{} // [Class webfrontend.gui.Rankings.ChallengesDataModel]
   declare module webfrontend.gui.RecrutingWidget{} // [Class webfrontend.gui.RecrutingWidget]
   declare module webfrontend.gui.ReportAbusePage{} // [Class webfrontend.gui.ReportAbusePage]
   declare module webfrontend.gui.ReportListWidget{} // [Class webfrontend.gui.ReportListWidget]
   declare module webfrontend.gui.ReportPage{} // [Class webfrontend.gui.ReportPage]
   declare module webfrontend.gui.ReportPageArmyCont{} // [Class webfrontend.gui.ReportPageArmyCont]
   declare module webfrontend.gui.ReportPageArmyGrid{} // [Class webfrontend.gui.ReportPageArmyGrid]
   declare module webfrontend.gui.ResearchOverviewWidget{} // [Class webfrontend.gui.ResearchOverviewWidget]
   declare module webfrontend.gui.ResearchWidget{} // [Class webfrontend.gui.ResearchWidget]
   declare module webfrontend.gui.RetreatUnitsWidget{} // [Class webfrontend.gui.RetreatUnitsWidget]
   declare module webfrontend.gui.RewardsWidget{} // [Class webfrontend.gui.RewardsWidget]
   declare module webfrontend.gui.SelBoxContinentFilter{} // [Class webfrontend.gui.SelBoxContinentFilter]
   declare module webfrontend.gui.SelCities{} // [Class webfrontend.gui.SelCities]
   declare module webfrontend.gui.SelCityGroups{} // [Class webfrontend.gui.SelCityGroups]
   declare module webfrontend.gui.SendArmyWindow{} // [Class webfrontend.gui.SendArmyWindow]
   declare module webfrontend.gui.ServerBarWidget{} // [Class webfrontend.gui.ServerBarWidget]
   declare module webfrontend.gui.ShopNotEnoughFundsPopup{} // [Class webfrontend.gui.ShopNotEnoughFundsPopup]
   declare module webfrontend.gui.ShopPlayerSpecialOfferItem{} // [Class webfrontend.gui.ShopPlayerSpecialOfferItem]
   declare module webfrontend.gui.ShopSpecialOfferItem{} // [Class webfrontend.gui.ShopSpecialOfferItem]
   declare module webfrontend.gui.ShopWidget{} // [Class webfrontend.gui.ShopWidget]
   declare module webfrontend.gui.ShrineDetailView{} // [Class webfrontend.gui.ShrineDetailView]
   declare module webfrontend.gui.Social.FriendsPage{} // [Class webfrontend.gui.Social.FriendsPage]
   declare module webfrontend.gui.Social.IgnorePage{} // [Class webfrontend.gui.Social.IgnorePage]
   declare module webfrontend.gui.Social.InvitationsPage{} // [Class webfrontend.gui.Social.InvitationsPage]
   declare module webfrontend.gui.Social.MainWidget{} // [Class webfrontend.gui.Social.MainWidget]
   declare module webfrontend.gui.SpecialOfferPopupWindow{} // [Class webfrontend.gui.SpecialOfferPopupWindow]
   declare module webfrontend.gui.StatisticsWidget{} // [Class webfrontend.gui.StatisticsWidget]
   declare module webfrontend.gui.SubstituteItem{} // [Class webfrontend.gui.SubstituteItem]
   declare module webfrontend.gui.SubstituteReqItem{} // [Class webfrontend.gui.SubstituteReqItem]
   declare module webfrontend.gui.SubstitutionContacts{} // [Class webfrontend.gui.SubstitutionContacts]
   declare module webfrontend.gui.SystemMessageWindow{} // [Class webfrontend.gui.SystemMessageWindow]
   declare module webfrontend.gui.TitleWidget{} // [Class webfrontend.gui.TitleWidget]
   declare module webfrontend.gui.Trade.MainWidget{} // [Class webfrontend.gui.Trade.MainWidget]
   declare module webfrontend.gui.Trade.OtherOffersPage{} // [Class webfrontend.gui.Trade.OtherOffersPage]
   declare module webfrontend.gui.Trade.OwnOffersPage{} // [Class webfrontend.gui.Trade.OwnOffersPage]
   declare module webfrontend.gui.Trade.PurifyResourcesPage{} // [Class webfrontend.gui.Trade.PurifyResourcesPage]
   declare module webfrontend.gui.Trade.RequestResourcesPage{} // [Class webfrontend.gui.Trade.RequestResourcesPage]
   declare module webfrontend.gui.Trade.SendResourcesPage{} // [Class webfrontend.gui.Trade.SendResourcesPage]
   declare module webfrontend.gui.TradeInfoPage{} // [Class webfrontend.gui.TradeInfoPage]
   declare module webfrontend.gui.TradeMinisterOptionsPage{} // [Class webfrontend.gui.TradeMinisterOptionsPage]
   declare module webfrontend.gui.TreeRowRendererCustom{} // [Class webfrontend.gui.TreeRowRendererCustom]
   declare module webfrontend.gui.UnitQueue{} // [Class webfrontend.gui.UnitQueue]
   declare module webfrontend.gui.Util{} // Object
   declare module webfrontend.gui.UtilQuickUse{} // Object
   declare module webfrontend.gui.WelcomeWidget{} // [Class webfrontend.gui.WelcomeWidget]
   declare module webfrontend.gui.WndEditPreviewSaveText{} // [Class webfrontend.gui.WndEditPreviewSaveText]
   declare module webfrontend.gui.WorldMapConfig{} // [Class webfrontend.gui.WorldMapConfig]
   declare module webfrontend.gui.WorldMapHelper{} // Object
   declare module webfrontend.gui.WorldMapLegendWindow{} // [Class webfrontend.gui.WorldMapLegendWindow]
   declare module webfrontend.gui.WorldToolTip{} // [Class webfrontend.gui.WorldToolTip]
   declare module webfrontend.gui.layout.FileService{} // [Class webfrontend.gui.layout.FileService]
   declare module webfrontend.gui.layout.Loader{} // [Class webfrontend.gui.layout.Loader]
   declare module webfrontend.math.Vector2{} // [Class webfrontend.math.Vector2]
   declare module webfrontend.net.CommandManager{} // [Class webfrontend.net.CommandManager]
   declare module webfrontend.net.UpdateManager{} // [Class webfrontend.net.UpdateManager]
   declare module webfrontend.quest.Main{} // [Class webfrontend.quest.Main]
   declare module webfrontend.res.Challenges{} // [Class webfrontend.res.Challenges]
   declare module webfrontend.res.Main{} // [Class webfrontend.res.Main]
   declare module webfrontend.res.llcomp{} // [Class webfrontend.res.llcomp]
   declare module webfrontend.ui.AllianceLabel{} // [Class webfrontend.ui.AllianceLabel]
   declare module webfrontend.ui.AllianceRewardElementPopup{} // [Class webfrontend.ui.AllianceRewardElementPopup]
   declare module webfrontend.ui.BrandBoostRedemption{} // [Class webfrontend.ui.BrandBoostRedemption]
   declare module webfrontend.ui.BrandBoostWrapper{} // [Class webfrontend.ui.BrandBoostWrapper]
   declare module webfrontend.ui.ButtonContainer{} // [Class webfrontend.ui.ButtonContainer]
   declare module webfrontend.ui.CellRendererHtmlCustom{} // [Class webfrontend.ui.CellRendererHtmlCustom]
   declare module webfrontend.ui.CellrendererBooleanExtra{} // [Class webfrontend.ui.CellrendererBooleanExtra]
   declare module webfrontend.ui.CityCoordLabel{} // [Class webfrontend.ui.CityCoordLabel]
   declare module webfrontend.ui.CityLabel{} // [Class webfrontend.ui.CityLabel]
   declare module webfrontend.ui.CollapseContainer{} // [Class webfrontend.ui.CollapseContainer]
   declare module webfrontend.ui.ColorPopupCustom{} // [Class webfrontend.ui.ColorPopupCustom]
   declare module webfrontend.ui.ColorSelectorCustom{} // [Class webfrontend.ui.ColorSelectorCustom]
   declare module webfrontend.ui.ContainerButton{} // [Class webfrontend.ui.ContainerButton]
   declare module webfrontend.ui.CustomSelectBox{} // [Class webfrontend.ui.CustomSelectBox]
   declare module webfrontend.ui.CustomTable{} // [Class webfrontend.ui.CustomTable]
   declare module webfrontend.ui.CustomWindow{} // [Class webfrontend.ui.CustomWindow]
   declare module webfrontend.ui.DateChooser{} // [Class webfrontend.ui.DateChooser]
   declare module webfrontend.ui.DateChooserButton{} // [Class webfrontend.ui.DateChooserButton]
   declare module webfrontend.ui.DateTimeChooser{} // [Class webfrontend.ui.DateTimeChooser]
   declare module webfrontend.ui.FixedSizeLabel{} // [Class webfrontend.ui.FixedSizeLabel]
   declare module webfrontend.ui.MessageBox{} // Object
   declare module webfrontend.ui.MgrValueChange{} // [Class webfrontend.ui.MgrValueChange]
   declare module webfrontend.ui.MultirowTabViewWidget{} // [Class webfrontend.ui.MultirowTabViewWidget]
   declare module webfrontend.ui.PlayerLabel{} // [Class webfrontend.ui.PlayerLabel]
   declare module webfrontend.ui.QuickUseButton{} // [Class webfrontend.ui.QuickUseButton]
   declare module webfrontend.ui.RewardPreviewButton{} // [Class webfrontend.ui.RewardPreviewButton]
   declare module webfrontend.ui.RichHeaderCell{} // [Class webfrontend.ui.RichHeaderCell]
   declare module webfrontend.ui.RowRendererCustom{} // [Class webfrontend.ui.RowRendererCustom]
   declare module webfrontend.ui.ScrollContainerCustom{} // [Class webfrontend.ui.ScrollContainerCustom]
   declare module webfrontend.ui.SelectBoxImageHeader{} // [Class webfrontend.ui.SelectBoxImageHeader]
   declare module webfrontend.ui.ShrineLabel{} // [Class webfrontend.ui.ShrineLabel]
   declare module webfrontend.ui.SoundButton{} // [Class webfrontend.ui.SoundButton]
   declare module webfrontend.ui.SoundToggleButton{} // [Class webfrontend.ui.SoundToggleButton]
   declare module webfrontend.ui.SpinnerInt{} // [Class webfrontend.ui.SpinnerInt]
   declare module webfrontend.ui.TableCellEditorSelectBoxCustom{} // [Class webfrontend.ui.TableCellEditorSelectBoxCustom]
   declare module webfrontend.ui.TableCellRendererReplaceCustom{} // [Class webfrontend.ui.TableCellRendererReplaceCustom]
   declare module webfrontend.ui.TableHeaderCellRendererIconRichTT{} // [Class webfrontend.ui.TableHeaderCellRendererIconRichTT]
   declare module webfrontend.ui.TableHeaderCellRendererRichTT{} // [Class webfrontend.ui.TableHeaderCellRendererRichTT]
   declare module webfrontend.ui.TablePaneScrollerCustom{} // [Class webfrontend.ui.TablePaneScrollerCustom]
   declare module webfrontend.vis.CityBuilding{} // [Class webfrontend.vis.CityBuilding]
   declare module webfrontend.vis.CityBuildingPlace{} // [Class webfrontend.vis.CityBuildingPlace]
   declare module webfrontend.vis.CityFortification{} // [Class webfrontend.vis.CityFortification]
   declare module webfrontend.vis.CityObject{} // [Class webfrontend.vis.CityObject]
   declare module webfrontend.vis.CityResField{} // [Class webfrontend.vis.CityResField]
   declare module webfrontend.vis.CityWallLevel{} // [Class webfrontend.vis.CityWallLevel]
   declare module webfrontend.vis.Entity{} // [Class webfrontend.vis.Entity]
   declare module webfrontend.vis.Main{} // [Class webfrontend.vis.Main]
   declare module webfrontend.vis.Util{} // Object}

